### PR TITLE
fix(api): correct the response by the health api 

### LINKED ISSUE #104: Improve implementation of /health endpoint
### Description
In the ```/health``` endpoint, despite the database connection with application being set up properly, it returns ```Internal Server Error``` if there are no licenses in the database.

#### Desired Behaviour:
The endpoint should return ```Internal Server Error``` only if the database connection is not set up properly.

#### Fix:
Check health with a simple ping to the database and not a query to the licenses table.

### PR DESCRIPTION
**Pull request by ChayanDass**
## Changes

- Closes #104 
- Fixed the health check API to properly handle the case when no records exist but the database is still connected.
- Updated the logic to check the database connection using `.Ping()`.
- Ensures the API returns `"Database is running and connected"` even if no licenses are found.

## Submitter Checklist

- [ ] Includes tests (if there is a feature changed/added)
- [ ] Includes docs (if changes are user-facing)
- [x] I have tested my changes locally.

## References

- when db is connected
Screenshot from 2025-03-13 01-18-21

- when failed to connect with the db 
Screenshot from 2025-03-13 01-17-52

### CODE REVIEW

**Comment by ChayanDass** [comment]
@deo002     Let me know if you need any modifications! 🚀

**Comment by deo002** [comment]
Thanks a lot for the contributions @ChayanDass! I'll review the PR shortly. 

Just a small suggestion for future contributions: it would be super helpful to open an issue first before submitting a PR. That way, we can discuss the idea with the community and ensure everyone's on the same page. I'll go ahead and create one on your behalf for this PR. 😊

File: pkg/api/api.go [hunk 1]
```diff
@@ -294,24 +295,54 @@ func HandleInvalidUrl(c *gin.Context) {
...
+			Error:     err.Error(),
+			Path:      c.Request.URL.Path,
+			Timestamp: time.Now().Format(time.RFC3339),
+		}
+		c.JSON(http.StatusInternalServerError, er)
+		return
+	}
+
+	// Try to fetch one license record
 	var license models.LicenseDB
```
Comment (deo002) [inline pkg/api/api.go:317]: The logic to check for a license entry in table is not needed. A ping to the database should suffice.

**Review by deo002 — CHANGES_REQUESTED** [review]

File: pkg/api/api.go (hunk 1 above)
Comment (ChayanDass) [reply pkg/api/api.go:317]: func GetHealth(c *gin.Context) {
	// Check if the database connection is active
	sqlDB, err := db.DB.DB()
	if err == nil {
		err = sqlDB.Ping()
	}
	// If database is not connnected, return an error response
	if err != nil {
		er := models.LicenseError{
			Status:    http.StatusInternalServerError,
			Message:   "Database is not running or connected",
			Error:     err.Error(),
			Path:      c.Request.URL.Path,
			Timestamp: time.Now().Format(time.RFC3339),
		}
		c.JSON(http.StatusInternalServerError, er)
		return
	}
	// If the database is connected and no error, return success
	er := models.LicenseError{
		Status:    http.StatusOK,
		Message:   "Database is running and connected",
		Error:     "",
		Path:      c.Request.URL.Path,
		Timestamp: time.Now().Format(time.RFC3339),
	}
	c.JSON(http.StatusOK, er)
}   .....   is this sufficient?

**Comment by deo002** [comment]
Tested, working as expected
image

Just squash the commits and we'll merge it.

**Comment by ChayanDass** [comment]
Done sir!

**Comment by deo002** [comment]
One last thing Chayan, all your commits must have verified signatures. You can check it out [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

**Comment by ChayanDass** [comment]
done sir !

**Review by deo002 — APPROVED** [review]

**Comment by deo002** [comment]
> done sir !

Thanks a lot for the contributions!
