### PR TITLE
fix(update_license): License update endpoint and it's documentation fixed

### LINKED ISSUE #109: PATCH /licenses/{shortname} not working as expected
### Description
- ```PATCH /licenses/{shortname}``` endpoint documentation has disappeared from swagger docs.
- Endpoint is throwing ```Internal Server Error```

### PR DESCRIPTION
**Pull request by deo002**
## Changes

- Swagger documentation was not being detected because of variable declaration before function and after comments for swagger docs.
- The ```validateLicenseFields``` function was called even when the key value for spdx_id in payload was undefined in ```BeforeUpdate``` hook of licenses, causing nil dereference error.
- Closes #109 

## Submitter Checklist

- [ ] Includes tests (if there is a feature changed/added)
- [X] Includes docs ( if changes are user facing)
- [X] I have tested my changes locally.

### CODE REVIEW

File: pkg/models/types.go [hunk 1]
```diff
@@ -92,12 +92,13 @@ func validateLicenseFields(l *LicenseDB) error {
...
-		valid, _ := spdxexp.ValidateLicenses([]string{*l.SpdxId})
-		if !valid {
-			return errors.New("spdx_id does not follow spdx license expression specifications")
+	if l.SpdxId != nil {
+		if *l.SpdxId == "" {
+			return errors.New("spdx_id cannot be an empty string")
+		} else {
+			if valid, _ := spdxexp.ValidateLicenses([]string{*l.SpdxId}); !valid {
+				return errors.New("spdx_id does not follow spdx license expression specifications")
+			}
```
Comment (avinal) [inline pkg/models/types.go:101]: This is a confusing change. Why did we have to use nested if and spread the logic instead of making it concise? Am I missing something?

Comment (deo002) [reply pkg/models/types.go:101]: In the current code:
```
	if l.SpdxId != nil && *l.SpdxId == "" {
		return errors.New("spdx_id cannot be an empty string")
	} else {
		valid, _ := spdxexp.ValidateLicenses([]string{*l.SpdxId})
		if !valid {
			return errors.New("spdx_id does not follow spdx license expression specifications")
		}
	}
``` 
In case of license update, ```l.SpdxId``` can be ```nil```. In that case, code flow will enter else condition and we'll get a nil pointer dereference error for it.

**Review by GMishx — APPROVED** [review]
Changes looks good.
