### PR TITLE
fix(audit): handle audit_id=0 and changelog_id=0 correctly in Audit APIs 

### LINKED ISSUE #123: Incorrect Handling of Audit and Changelog IDs in Audit APIs
## Description
The following functions in the Audit module have issues related to incorrect handling of `audit_id` and `changelog_id`, leading to unintended API behavior.  

###  Issues in `GetChangeLogs` 
1. `audit_id=0` returns all changelogs instead of an error
   - When requesting changelogs with `audit_id=0`, the API unexpectedly returns all available changelogs in the system instead of rejecting the request.  

#### Steps to Reproduce (`GetChangeLogs`) 
1. Start the server and ensure there are multiple audit changelog entries.  
2. Make a `GET` request with `audit_id=0`:  
   ```bash
   curl -X 'GET' 'http://localhost:8080/api/v1/audits/0/changes' \
   -H 'accept: application/json' \
   -H 'Authorization: Bearer <TOKEN>'
   ```
3. Expected Response:  
   - `400 Bad Request: Invalid audit ID`  
4. Actual Response:  
   - Returns all changelog records instead of an error.  

### Issues in `GetChangeLogById` 
1. `changelog_id=0` is incorrectly treated as `1`  
   - When requesting a changelog with `changelog_id=0`, the API incorrectly returns the changelog with `id=1`.  

#### Steps to Reproduce (`GetChangeLogById`)
1. Ensure there is a changelog entry with `id=1`.  
2. Make a `GET` request with `changelog_id=0`:  
   ```bash
   curl -X 'GET' 'http://localhost:8080/api/v1/audits/1/changes/0' \
   -H 'accept: application/json' \
   -H 'Authorization: Bearer <TOKEN>'
   ```
3. Expected Response:  
   - `400 Bad Request: Invalid changelog ID`  
4. Actual Response:  
   - Returns changelog with `id=1`, instead of rejecting the request.  

### Issues in `GetAudit` 
1. `audit_id=0` returns the first audit record instead of an error
   - When requesting an audit record with `audit_id=0`, the API incorrectly returns the first available audit record in the database.  

#### Steps to Reproduce (`GetAudit`)  
1. Ensure there are audit records available in the database.  
2. Make a `GET` request with `audit_id=0`:  
   ```bash
   curl -X 'GET' 'http://localhost:8080/api/v1/audits/0' \
   -H 'accept: application/json' \
   -H 'Authorization: Bearer <TOKEN>'
   ```
3. Expected Response:  
   - `400 Bad Request: Invalid audit ID`  
4. Actual Response:  
   - Returns the first audit record instead of an error.  

### Cause
This happens because GORM’s struct-based query does not properly handle `0` as an invalid value, which may treat an empty condition as fetching the first available record.

### PR DESCRIPTION
**Pull request by Vaibhavsahu2810**
## Changes

- Modified functions to use direct SQL queries with parameters instead of struct-based queries
- Fixes #123 

## Submitter Checklist

- [ ] Includes tests (if there is a feature changed/added)
- [ ] Includes docs ( if changes are user facing)
- [x] I have tested my changes locally.

### CODE REVIEW

**Comment by Vaibhavsahu2810** [comment]
@deo002 , can you please review this pr ?

File: pkg/api/audit.go [hunk 1]
```diff
@@ -145,7 +145,7 @@ func GetChangeLogs(c *gin.Context) {
 		return
 	}
 
-	result := db.DB.Where(models.ChangeLog{AuditId: parsedId}).Find(&changelog)
+	result := db.DB.Where("audit_id = ?", parsedId).Find(&changelog)
```
Comment (deo002) [inline pkg/api/audit.go:148]: It will be better to use GORM struct field names instead of sql field names.

If the sql field values ever change, we would have to change them in a lot of places in the codebase.

An if else condition checking for 0 should do.

**Comment by shaheemazmalmmd** [comment]
@Vaibhavsahu2810 : Please look into the changes recommended by @deo002

**Comment by Vaibhavsahu2810** [comment]
Made changes as requested !!
